### PR TITLE
Hopefully useful changes that make it easier to reuse reSnap

### PR DESCRIPTION
**Pull request by Folcon**
reSnap is currently being used by [obsidian-remarkable](https://github.com/cobalamin/obsidian-remarkable).

I noticed that some minor changes would ease compatibility as well as hopefully make reSnap easier to use with other use-cases.

### CODE REVIEW

**Comment by cloudsftp** [comment]
I don't see how this fixes your problem.
Your shell knows where the command is otherwise `$(command -v ffmpeg)` would turn up empty right?

Could you please enlighten me.

**Comment by Folcon** [comment]
@cloudsftp, I'm not sure what the shell node is invoking exactly, but I hit this error on my mac.

Specifically this one:
```
VM149:29 Uncaught (in promise) Nonzero exitcode.
STDERR: /Users/folcon/.local/bin/reSnap.sh: line 163: ffmpeg: command not found
/Users/folcon/.local/bin/reSnap.sh: line 162: lz4: command not found
```
[Referenced here](https://github.com/cobalamin/obsidian-remarkable/issues/6#issuecomment-1125605850).

This is what made me dig into it, I tried `which`, which found the correct path, but I thought it would be better to not depend on `which` being available and instead use a shell built-in.

**Comment by cloudsftp** [comment]
Hey can you change the branch of the pull request to [this one](https://github.com/cloudsftp/reSnap/tree/feature/binaries_abspath)? I want to do some changes.

As for the display option. I want to keep the default behavior as displaying the screenshot.
Does an environment variable like `RESNAP_DISPLAY` work for you? And of course the inverted option `--no-display`.

**Comment by Folcon** [comment]
@cloudsftp
> Hey can you change the branch of the pull request to [this one](https://github.com/cloudsftp/reSnap/tree/feature/binaries_abspath)? I want to do some changes.

Looking in the UI I don't believe I can make the head of this PR into a different branch, what I can change is the merge target, but I doubt that would be useful?

You can cherry-pick or push you commits onto this branch or we could close this PR and instead make one based off of [feature/binaries_abspath](https://github.com/cloudsftp/reSnap/tree/feature/binaries_abspath) if you'd prefer?

If there are write issues, I could pull your changes onto this branch as well =)...

Though I'm not sure why that would be the case.
 
> As for the display option. I want to keep the default behavior as displaying the screenshot. Does an environment variable like `RESNAP_DISPLAY` work for you? And of course the inverted option `--no-display`.

I'd probably use the `--no-display` as that seems to already be what's used by [obsidian-remarkable](https://github.com/cobalamin/obsidian-remarkable), but I like the idea of an ENV VAR, options like that just end up being useful for some use cases.

**Comment by cloudsftp** [comment]
Alright, I'm just gonna merge it without a new PR and close this one.

**Comment by Folcon** [comment]
Thanks =)...

**Pull request closed without merging**
